services: docker
env:
  matrix:
    - distro: rhel6
      epel: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
      init: "/sbin/init"
      run_opts: ''
    - distro: rhel7
      epel: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      init: "/usr/lib/systemd/systemd"
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
- docker pull registry.access.redhat.com/$distro

script:
- container_id=$(mktemp)

- docker run --detach ${run_opts} registry.access.redhat.com/$distro "${init}" > "${container_id}"

- docker exec --tty "$(cat ${container_id})" env TERM=xterm RH_USER=$RH_USER RH_PASS=$RH_PASS bash -c 
  "subscription-manager register --username $RH_USER --password $RH_PASS --autosubscribe; (exit $?)"

- docker exec --tty "$(cat ${container_id})" env TERM=xterm epel=$epel bash -c 
  "yum install -y $epel; (exit $?) && yum -y update"

- docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c
  'yum --disableplugin=fastestmirror -y --enablerepo=epel-testing install ansible &&
  yum -y update && yum clean all; (exit $?)'

- docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c 
  'ansible localhost -c local -m ping; (exit $?)'

after_success:
  - docker login --username nousdefions --password $DOCKERHUB_PASS
  - docker commit -m "Ansiblized" -a "Jonathan Davila" $(cat ${container_id}) nousdefions/ansible_$distro:latest 
  - docker push nousdefions/ansible_$distro

after_script:
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm subscription-manager unregister 

